### ISSUE TITLE
reaserch osu .osu files format

### ISSUE THREAD

**Issue by Hefadog2** [GSSTRhythmGame2021/DataAcquisition#13]
for 4 button version

**Comment by Skelly57** [comment]
zip file underneath, can use any archiver (ex: 7zip) to open it

**Comment by Skelly57** [comment]
[Here's the documentation for the .osu file format](https://osu.ppy.sh/wiki/en/osu!_File_Formats/Osu_(file_format))

Included is a .osu file in a txt format, github won't let me attach the file itself, I'll upload it into the slack.

So far the .osu file is mainly concerned with the timing of notes and the placing of them on the screen, do read the documentation for more info about the specifics.

[Osu File Text Form.txt](https://github.com/GSSTRhythmGame2021/DataAcquisition/files/7590576/Osu.File.Text.Form.txt)

**Comment by Skelly57** [comment]
Here's a file for a song made for osu!taiko, which is osu's 4 button beatmap system. Again, github won't let me upload an osu file so I'll post this in the slack as well

[Osu Four Button Form.txt](https://github.com/GSSTRhythmGame2021/DataAcquisition/files/7590652/Osu.Four.Button.Form.txt)

**Comment by Hefadog2** [comment]
Make a file with the correct formating to show knowledge

**Comment by beyondtherice** [comment]
[HitObjects]
77,171,8733,6,0,B|144:108|144:108|212:108,2,160,0|0|2,0:0|0:0|0:0,0:0:0:0:
180,292,10139,1,0,0:0:0:0:
248,332,10374,1,0,0:0:0:0:
328,332,10608,2,0,P|365:266|321:206,1,160,2|0,0:0|0:0,0:0:0:0:
216,80,11546,2,0,P|172:141|211:207,1,160,2|0,0:0|0:0,0:0:0:0:
292,196,12249,5,0,0:0:0:0:
292,196,12483,2,0,P|331:190|363:167,1,80,2|0,0:0|0:0,0:0:0:0:
392,92,12952,2,0,P|386:52|360:16,1,80,2|0,0:0|0:0,0:0:0:0

Every line describes distinctive beatmap interaction "hit" event + info the game needs to render information. (timestamp/position data)

We need to create path coordinates/"hit" vectors/arrays for objects to generate across position and object value

.osu files : encode hit object positions
.osz : full  : encode logic position and visual cues in sync with music
