### ISSUE TITLE
Goal

### ISSUE THREAD

**Issue by Hefadog2** [GSSTRhythmGame2021/DataAcquisition#14]
Modify code to make a beat map that makes you click on 1 button per downbeat

**Comment by Skelly57** [comment]
once this works, simple expansion is to pick an attribute (not BPM) and make it change the key pressed

**Comment by Hefadog2** [comment]
We can make the subdivisions of beats into notes based on factors such as emphasis or find the timbre of the percussion oto combine notes together and create more variety
