### ISSUE TITLE
Use pre-commit hooks

### ISSUE THREAD

**Issue by Skelly57** [GSSTRhythmGame2021/DataAcquisition#20]
Similar to github actions but runs locally on commits, as opposed to when it's pushed to github, where it's often too late to make efficient changes. Runs our dependencies locally before being pushed, in case something goes wrong.

**Comment by beyondtherice** [comment]
Pre-commit hook file is now set and works. Clarify what kinds of dependencies/libraries you want to use for the pre commit hooks.
