### ISSUE TITLE
Use Semgrep

### ISSUE THREAD

**Issue by Hefadog2** [GSSTRhythmGame2021/DataAcquisition#7]
Semgrep is a static code analysis tool to find bugs and enforce standards
add as dev depenadcy

**Comment by Skelly57** [comment]
added to repo

**Comment by Hefadog2** [comment]
Working Smoothly
```poetry run semgrep acquisition.py --config auto                                                                                                        Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on your languages and frameworks.                                                                                                                                                                                                               Logging in to the Semgrep Registry as project 'https://github.com/GSSTRhythmGame2021/DataAcquisition.git'...                                                                                                                                 Fetching rules from https://semgrep.dev/registry ...                                                                                                                                                                                         Running 135 rules...                                                                                                                                                                                                                         100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|135/135ran 135 rules on 1 files: 0 findings    ```

**Comment by Hefadog2** [comment]
run on whole repo

**Comment by Skelly57** [comment]
run again after all changes are merged w/ master

**Comment by Skelly57** [comment]
ran semgrep on the whole repo
```
$ poetry run semgrep --config auto .
Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on
your languages and frameworks.
Logging in to the Semgrep Registry as project 'https://github.com/GSSTRhythmGame2021/DataAcquisition.git'...
Fetching rules from https://semgrep.dev/registry ...
Running 135 rules...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|135/135
ran 135 rules on 4 files: 0 findings
```

should be good to close 👍
