### ISSUE TITLE
Use mypy

### ISSUE THREAD

**Issue by Hefadog2** [GSSTRhythmGame2021/DataAcquisition#8]
mypy is types, it implements types for python to make sure define classes and function types
add as dev dependancy

**Comment by Skelly57** [comment]
added to repo

**Comment by Hefadog2** [comment]
mypy returns several errors on the imports but these are not serious errors and it is setting the type to any rather than specific stubs that will require a different library
```poetry run mypy acquisition.py                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   acquisition.py:1: error: Skipping analyzing "spotipy": found module but no type hints or library stubs                                                                                                                                       acquisition.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports                                                                                                                                          acquisition.py:3: error: Skipping analyzing "spotipy.oauth2": found module but no type hints or library stubs                                                                                                                                acquisition.py:4: error: Skipping analyzing "spotipy.util": found module but no type hints or library stubs                                                                                                                                  acquisition.py:5: error: Skipping analyzing "pandas": found module but no type hints or library stubs                                                                                                                                        acquisition.py:6: error: Skipping analyzing "matplotlib.pyplot": found module but no type hints or library stubs                                                                                                                             acquisition.py:6: error: Skipping analyzing "matplotlib": found module but no type hints or library stubs                                                                                                                                    Found 6 errors in 1 file (checked 1 source file) ```

**Comment by Hefadog2** [comment]
see if possible to integrate mypy.ini into .toml

**Comment by Skelly57** [comment]
after merge #19, run mypy again and sort into functions
