### ISSUE TITLE
Use githubacctions to run checks for pull requests

### ISSUE THREAD

**Issue by Hefadog2** [GSSTRhythmGame2021/DataAcquisition#9]
when ever you get a pull request it will run all dependencies and if they fail it will not merge
quality control

**Comment by Skelly57** [comment]
github actions has been made but isort is skipping a file, need to figure out why

**Comment by Skelly57** [comment]
have black and other dependencies return an exit code if errors are spotted

**Comment by Skelly57** [comment]
also update pyporject.toml w/ up to date semgrep

**Comment by Skelly57** [comment]
currently the isort issue is solved an pylint returns an exit code when spotting errors

**Comment by Skelly57** [comment]
bandit returns an exit code when spotting errors, just need to fix the current error for updated dependencycheck.yml to pass

**Comment by Skelly57** [comment]
currently isort will swap imports around when doing a dependency check, need to switch command to poetry run isort . --diff -v to only show changes. also doesn't return an exit code after showing (or making) changes
